module.exports = [
  {
    ignores: [
      "models/",
      "venv-llm/",
      "venv-rag/",
      "src/",
      "bin/",
      "logs/",
      "app/data/",
    ],
  },
  {
    files: ["app/static/app.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        document: "readonly",
        window: "readonly",
        fetch: "readonly",
        console: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        EventSource: "readonly",
        AbortController: "readonly",
        FormData: "readonly",
        URLSearchParams: "readonly",
        TextDecoder: "readonly",
        alert: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { args: "none" }],
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-cond-assign": "error",
      "no-func-assign": "error",
      "no-redeclare": "error",
      "no-extra-semi": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-constant-condition": "error",
      "no-unsafe-finally": "error",
      "no-useless-escape": "error",
      "no-prototype-builtins": "error",
      "valid-typeof": "error",
    },
  },
];